# Source global definitions
if [ -f /etc/bashrc ]; then
    . /etc/bashrc
fi

### Load support files.
for file in ~/.bash/[0-9][0-9]*; do
    source $file
done

export PERLBREW_ROOT=/wsb/perl5
source /wsb/perl5/etc/bashrc
